# Generated by Django 3.2.3 on 2021-06-26 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subject', '0003_merge_0002_auto_20210622_0937_0002_classcode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='classRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_no', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('classcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.classcode')),
                ('subjectTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
