# Generated by Django 3.2.3 on 2021-08-02 10:38

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210622_0937'),
        ('subject', '0003_merge_0002_auto_20210622_0937_0002_classcode_code'),
        ('classRoutine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroutine',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='classroutine',
            name='subjectcode',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='subject.subjectcode'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='subjectTeacher',
            field=models.ForeignKey(default='ishar', on_delete=django.db.models.deletion.CASCADE, to='user.teacher'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='time',
            field=models.CharField(default='25', max_length=100),
        ),
    ]
