# Generated by Django 3.2.3 on 2021-08-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classRoutine', '0003_alter_classroutine_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='subjectTeacher',
            field=models.CharField(max_length=100),
        ),
    ]
