# Generated by Django 3.2.3 on 2021-08-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_merge_0002_auto_20210622_0937_0002_classcode_code'),
        ('classRoutine', '0005_auto_20210803_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroutine',
            name='classcode',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='subject.classcode'),
        ),
        migrations.AlterField(
            model_name='classroutine',
            name='subjectcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.subjectcode'),
        ),
    ]
