# Generated by Django 3.2.5 on 2021-08-02 10:13

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0005_auto_20210622_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='file',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='posted_By',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notes',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx', 'docx'])]), null=True, size=4),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
