# Generated by Django 3.2.5 on 2021-08-02 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_merge_0002_auto_20210622_0937_0002_classcode_code'),
        ('notes', '0006_auto_20210802_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='classcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.classcode'),
        ),
    ]
