# Generated by Django 3.2.5 on 2021-08-02 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_notes_classcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='files',
        ),
        migrations.AddField(
            model_name='notes',
            name='file',
            field=models.FileField(null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'ppt', 'xlsx', 'docx'])]),
        ),
    ]
