# Generated by Django 3.2.4 on 2021-06-10 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='classcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.classcode'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='subjectcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.subjectcode'),
        ),
    ]
