# Generated by Django 3.2.3 on 2021-06-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_notice_classcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='subj_code',
            field=models.CharField(default='COMP101', max_length=15),
        ),
    ]
