# Generated by Django 3.2.3 on 2021-06-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_alter_notice_classcode'),
        ('notice', '0004_auto_20210622_0937'),
    ]

    operations = [
    ]
