# Generated by Django 3.2.4 on 2021-06-08 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=150)),
                ('batch', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.classcode')),
                ('subjectcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subjectcode')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher')),
            ],
        ),
    ]
