# Generated by Django 3.2.3 on 2021-06-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_auto_20210622_0937'),
        ('subject', '0002_classcode_code'),
    ]

    operations = [
    ]
